In [27]:
#11

n = int(input("n을 입력하시오 : "))
idx = 0
sh = np.zeros(shape=(n,n))

for i in sh:
    i[:idx+1]=1
    idx+=1
    
print(sh)

n을 입력하시오 : 6
[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


In [69]:
#12
#산포도 그래프
import matplotlib.pyplot as plt
import numpy as np

#평균이 25이고 표준편차가 5 인 정규분포
ran = 25+5*np.random.randn(30) 


xData = np.arange(0,50)
yData = xData+ran

plt.axis([0,50,0,50])


plt.scatter(xData,yData,color = "blue")



ValueError: operands could not be broadcast together with shapes (50,) (30,) 

In [5]:
#13

import numpy as np

x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1,10) for i in range(100)]
x3 = [i + np.random.randint(1,50) for i in range(100)]
x4 = [np.random.randint(1,200) for i in range(100)]

res = np.corrcoef([x1,x2,x3,x4])

print(res)

##정답 : x2


[[1.         0.99580079 0.88846941 0.13883417]
 [0.99580079 1.         0.88514569 0.15422017]
 [0.88846941 0.88514569 1.         0.13541856]
 [0.13883417 0.15422017 0.13541856 1.        ]]
