In [8]:
#10.1
import numpy as np

num_arr = np.arange(1,21,1)
print(num_arr)
print(num_arr[::-1])
print(f"num_arr 내의 모든 원소의 합 :{sum(num_arr)}")
print(num_arr.reshape(5,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
num_arr 내의 모든 원소의 합 :210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [7]:
#10.2
import numpy as np
#1)
n_arr = np.arange(25)
n_arr = n_arr.reshape(5,5)
print(n_arr,"\n")

#2)
print(f"n_arr의 첫 원소 = {n_arr[0,0]}")
print(f"n_arr의 마지막 원소 = {n_arr[-1,-1]}\n")

#3)
print(n_arr[0:2],"\n")

#4)
print(n_arr[2:],"\n")

#5)
print(n_arr[::,::2],"\n")

#6)
print(n_arr[::2,::2],"\n")

#7)
n_arr = n_arr[0:2].flatten()
print(n_arr.reshape(5,2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

n_arr의 첫 원소 = 0
n_arr의 마지막 원소 = 24

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]] 

[[ 0  2  4]
 [10 12 14]
 [20 22 24]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
#10.3

#1)
a = np.random.rand(3,3)
print(a,"\n")

#2)
print(f"a의 원소들 중 최댓값 : {np.max(a)}")

#3)
print(f"a의 원소들 중 최댓값의 위치 : {np.argmax(a)}")



[[0.27010675 0.14840057 0.57016451]
 [0.30418073 0.95598444 0.94446295]
 [0.37082188 0.15733176 0.0201813 ]] 

a의 원소들 중 최댓값 : 0.955984443814412
a의 원소들 중 최댓값의 위치 : 4


In [3]:
#10.4
import numpy as np
a = np.random.randint(0,2,size = (5,5))
#1)
print(a,"\n")

#2)
idx = 0
arr = []
for i in a:
    arr.append(np.sum(a[idx]))
    idx+=1
    
arr = np.array(arr)
print(f"행렬의 행 방향 성분의 합 : {arr}")

[[0 0 1 1 0]
 [0 0 0 1 1]
 [1 0 0 1 1]
 [1 0 1 1 1]
 [1 1 0 1 0]] 

행렬의 행 방향 성분의 합 : [2 2 3 4 3]


In [66]:
#10.5

a = np.arange(0,32).reshape(4,4,2)
a = a.flatten()
print(a)
idx = 0
for i in a:
    idx+=1
    if idx == 10:
        print(f"10번째 원소 : {i}")
    elif idx == 20:
        print(f"20번째 원소 : {i}")


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
10번째 원소 : 9
20번째 원소 : 19


In [70]:
#10.6

x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1,10) for i in range(100)]
x3 = [i + np.random.randint(1,50) for i in range(100)]
x4 = [np.random.randint(1,100) for i in range(100)]

print(np.corrcoef([x1,x2,x3,x4]))

[[1.         0.99625687 0.92144401 0.06079385]
 [0.99625687 1.         0.91601808 0.06712937]
 [0.92144401 0.91601808 1.         0.06704231]
 [0.06079385 0.06712937 0.06704231 1.        ]]
