In [3]:
#10-1
import numpy as np

a = np.array(range(1,11))
b = np.array(range(10,101,10))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 11  22  33  44  55  66  77  88  99 110]
[ -9 -18 -27 -36 -45 -54 -63 -72 -81 -90]
[  10   40   90  160  250  360  490  640  810 1000]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [6]:
import numpy as np

a = np.array([1,2,3])
print(a.shape)        # a 객체의 형태(shape)
print(a.ndim)         # a 객체의 차원 
print(a.dtype)        # a 객체 내부 자료형
print(a.itemsize)     # a 객체 내부 자료형이 차지하는 메모리의 크기(byte)
print(a.size)         # a 객체의 전체 크기(항목의 수1)
print(a.strides)

(3,)
1
int64
8
3
(8,)


In [28]:
#10.2
a = np.array(range(1,11)) + np.array(range(10,101,10))
print(a.shape)
print(a.size)

(10,)
10


In [16]:
#LAB 10-1
import numpy as np
array_c = np.array(range(0,10,2))
print(f"실습 1 : array_a = {np.array([0,1,2,3,4,5,6,7,8,9])}")
print(f"실습 2 : array_a = {np.array(range(10))}")
print(f"실습 3 : array_c = {np.array(range(0,10,2))}")
print(f"실습 4 :")
print(array_c.shape)        # a 객체의 형태(shape)
print(array_c.ndim)         # a 객체의 차원 
print(array_c.dtype)        # a 객체 내부 자료형
print(array_c.itemsize)     # a 객체 내부 자료형이 차지하는 메모리의 크기(byte)
print(array_c.size)         # a 객체의 전체 크기(항목의 수1)


실습 1 : array_a = [0 1 2 3 4 5 6 7 8 9]
실습 2 : array_a = [0 1 2 3 4 5 6 7 8 9]
실습 3 : array_c = [0 2 4 6 8]
실습 4 :
(5,)
1
int64
8
5


In [20]:
#LAB 10-2

import numpy as np

h = np.array([1.83,1.76,1.69,1.86,1.77,1.73])
w = np.array([86,74,59,95,80,68])

bmi = w/h**2

print(f"대상자들의 몸무게 : {w}")
print(f"대상자들의 키 : {h}")
print(f"대상자들의 BMI : {bmi}")


대상자들의 몸무게 : [86 74 59 95 80 68]
대상자들의 키 : [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 BMI : [25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [23]:
#LAB 10-3
import numpy as np

x = np.array([['a','b','c','d'],['c','c','g','h']])
mat_a = np.array([[10,20,30],[10,20,30]])
mat_b = np.array([[2,2,2],[1,2,3]])

print(x[x=='c'])
print(mat_a-mat_b)

['c' 'c' 'c']
[[ 8 18 28]
 [ 9 18 27]]


In [41]:
#LAB 10-4
import numpy as np

x = np.array([[1.83,1.76,1.69,1.85,1.77,1.73],[86.0,74.0,59.0,95.0,80.0,68.0]])

y = x[0:2,1:3]
#[1.76,1.y69],[74.0,59.0]
z = x[0:2][1:3]
bmi = x[0]/x[1]**2
print(f"BMI data = {bmi}")

BMI data = [0.00024743 0.0003214  0.00048549 0.00020499 0.00027656 0.00037413]


In [1]:
#LAB 10-5
import numpy as np

players = [[170,76.4],[183,86.2],[181,78.5],[176,80.1]]
p = np.array(players)
print(f"몸무게가 80 이상인 선수 정보 {p[p[:,1]>=80.0]}")
print(f"키가 180 이상인 선수 정보 {p[p[:,0]>=180]}")

몸무게가 80 이상인 선수 정보 [[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보 [[183.   86.2]
 [181.   78.5]]


In [14]:
np.arange(0,6,2)
np.linspace(1,10,4)
np.logspace(0,5,11)

array([1.00000000e+00, 3.16227766e+00, 1.00000000e+01, 3.16227766e+01,
       1.00000000e+02, 3.16227766e+02, 1.00000000e+03, 3.16227766e+03,
       1.00000000e+04, 3.16227766e+04, 1.00000000e+05])

In [31]:
print(np.random.rand(5),"\n")     #0~1 사이의 난수 5개
print(np.random.rand(2,3),"\n")

a = 10
b = 20
print((b-a)*np.random.rand(5)+a,"\n") #10~20 사이의 난수 5개

print(np.random.randint(1,12,size=(3,4)),"\n")

mu = 10
sigma = 2 
randoms = mu + sigma * np.random.rand(5,4)    #평균값 10, 표준편차 = 2인  정규분포 5X4로 출력
print(randoms,"\n")
print(np.median(randoms),"\n")
print(np.mean(randoms),"\n")

[0.05794981 0.25660757 0.51033178 0.99525878 0.14651568] 

[[0.44951478 0.60144038 0.09727249]
 [0.28873488 0.7207999  0.55080606]] 

[18.38577015 15.80331351 11.84571737 16.15502117 18.86955088] 

[[11  9 10  3]
 [ 1 11  1  7]
 [ 9  7  5  8]] 

[[11.25946143 11.08377464 11.65122312 11.3556326 ]
 [11.38855325 10.43835701 11.80071479 10.26323241]
 [10.25250247 10.30639386 10.68761979 10.01693382]
 [10.26416385 11.45108649 11.65917803 10.02705636]
 [10.13403696 10.22370969 10.5905296  10.26956785]] 

10.514443305703875 

10.756186401843298 



In [33]:
#LAB 10-6
players = np.zeros((100,3))
players[:,0] = 10 * np.random.randn(100) + 175
players[:,1] = 10 * np.random.randn(100) + 70
players[:,2] = np.floor(10 * np.random.randn(100))+ 22

heights = players[:,0]
print(f"신장 평균값 : {np.mean(heights)}")
print(f"신장 중앙값 : {np.median(heights)}")

weights = players[:,1]
print(f"체중 평균값 : {np.mean(weights)}")
print(f"페중 중앙값 : {np.median(weights)}")

ages = players[:,2]
print(f"나이 평균값 : {np.mean(ages)}")
print(f"나이 중앙값 : {np.median(ages)}")

신장 평균값 : 175.62253202008662
신장 중앙값 : 176.16497030447783
체중 평균값 : 70.57661521603208
페중 중앙값 : 70.54395072582037
나이 평균값 : 20.47
나이 중앙값 : 19.0


In [35]:
x = [i for i in range(100)]
y = [i**2 for i in range(100)]

res = np.corrcoef(x,y)      # 상관관계 
print(res)

[[1.         0.96764439]
 [0.96764439 1.        ]]
